<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="Narasimharaos-MacBook-Pro.local" name="com.ibm.commerce.cmc.catalogs.testcases.CatalogUploadTest" tests="8" failures="2" timestamp="26 Feb 2019 11:58:31 GMT" time="11.200" errors="0">
  <testcase name="newCatalogUploadPageHeadTest" time="0.049" classname="com.ibm.commerce.cmc.catalogs.testcases.CatalogUploadTest"/>
  <testcase name="validateSaveButtonExistance" time="0.040" classname="com.ibm.commerce.cmc.catalogs.testcases.CatalogUploadTest"/>
  <testcase name="validateCloseButtonExistance" time="0.249" classname="com.ibm.commerce.cmc.catalogs.testcases.CatalogUploadTest"/>
  <testcase name="validateFileNameFieldTest" time="0.135" classname="com.ibm.commerce.cmc.catalogs.testcases.CatalogUploadTest"/>
  <testcase name="validateSizeFieldTest" time="0.109" classname="com.ibm.commerce.cmc.catalogs.testcases.CatalogUploadTest"/>
  <testcase name="validateCharacterSetFieldTest" time="0.106" classname="com.ibm.commerce.cmc.catalogs.testcases.CatalogUploadTest">
    <failure type="java.lang.AssertionError" message="expected [Character Set] but found [Charecter Set]">
      <![CDATA[java.lang.AssertionError: expected [Character Set] but found [Charecter Set]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.ibm.commerce.cmc.catalogs.testcases.CatalogUploadTest.validateCharacterSetFieldTest(CatalogUploadTest.java:78)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- validateCharacterSetFieldTest -->
  <testcase name="validateTargetCatalogFieldTest" time="0.043" classname="com.ibm.commerce.cmc.catalogs.testcases.CatalogUploadTest">
    <failure type="java.lang.AssertionError" message="expected [Target catalog] but found [Target Catalog]">
      <![CDATA[java.lang.AssertionError: expected [Target catalog] but found [Target Catalog]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.ibm.commerce.cmc.catalogs.testcases.CatalogUploadTest.validateTargetCatalogFieldTest(CatalogUploadTest.java:84)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- validateTargetCatalogFieldTest -->
  <testcase name="createNewCatalogUpload" time="10.469" classname="com.ibm.commerce.cmc.catalogs.testcases.CatalogUploadTest"/>
</testsuite> <!-- com.ibm.commerce.cmc.catalogs.testcases.CatalogUploadTest -->
